name: Shell Scripts Unit Testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Our ACA team script Unit test
      id: action-ACA-Devops-Bootcamp-Command-A 
      uses: Armen8793/ACA-Devops-Bootcamp-Command-A@main
    - name: CommandA-unittest result
      run: echo "The result of CommandA-unittest Action was ${{ steps.action-ACA-Devops-Bootcamp-Command-A.outputs.result }}"
    - name: Push changes
      if: github.ref == 'refs/heads/master'
      uses: Armen8793/ACA-Devops-Bootcamp-Command-A@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
