name: Shell Scripts Unit Testing

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
  
defaults:
  run:
    shell: bash  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Our ACA team script Unit test
      id: ACA-Devops-Bootcamp-Command-A 
      uses: Armen8793/ACA-Devops-Bootcamp-Command-A@Armen8793
    - name: CommandA-unittest result
      run: echo "The result of CommandA-unittest Action was ${{ steps.ACA-Devops-Bootcamp-Command-A.outputs.result }}"
      - name: Commit files
      run: |
        echo ${{ github.ref }}
        git add .
        git config --local user.email petrosyanarmen723@gmail.com
        git config --local user.name Armen8793
        git commit -m "CI: Automated build push" -a | exit 0
    - name: Push changes
    - name: Push changes
      if: github.ref == 'refs/heads/main'
      uses: Armen8793/ACA-Devops-Bootcamp-Command-A@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
