name: Tests

on: [push, pull_request]

jobs:
  run:
    runs-on: [ 'ubuntu-latest', 'windows-latest' ]
    strategy:
      matrix:
        nginx-versions: ['1.18.0']
    name: ${{ matrix.nginx-versions }} Test on ${{ matrix.os }}
- name: Checkout
  uses: actions/checkout@v2

- name: Setup PHP
  uses: shivammathur/setup-php@v2
  with:
    php-version: ${{ matrix.php-versions }}
    extensions: mbstring
    coverage: none
    tools: phpunit:${{ matrix.phpunit-version }}, composer:v2

- name: Check Nginx Version
  run: nginx -v

- name: Check Nginx status
  run: systemctl status nginx

- name: Restart nginx
  run: systemctl restart nginx

- name: Install PHP dependencies
  run: composer install --no-interaction --no-progress --no-suggest

- name: Run Test Suite
  run: vendor/bin/phpunit



    - name: Push changes
    - name: Push changes
      if: github.ref == 'refs/heads/main'
      uses: Armen8793/ACA-Devops-Bootcamp-Command-A@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
